# Generated by Django 6.1 on 2026-08-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
